services:
  - type: web
    name: amman-camera-violations
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DB_PATH
        value: /app/server/src/config/database.sqlite
      - key: UPLOADS_DIR
        value: /app/uploads
